name: older-than-2y
description: Older Than 2 Years Informer
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  slack_token:
    description: 'Slack Token'
    required: true
  debug:
    description: 'Debug mode'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '22.x'
    - id: npm
      run: cd ${{ github.action_path }}/../..; npm ci
      shell: bash
    - name: Older Than 2 Years Informer
      id: older-than-2y
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      env:
        DEBUG: ${{ (inputs.debug == 'true' || runner.debug) && 'true' || 'false'}}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const actionPath = '${{ github.action_path }}/../../'
          const inputs = ${{ toJson(inputs) }}

          const script = require('${{ github.action_path }}/action.cjs')
          await script({github, context, inputs, actionPath, core,
            debug: process.env.DEBUG === 'true'})
