version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "t3sts/**"
    open-pull-requests-limit: 10
    security-updates-only: true