on:
  pull_request_target:
  pull_request:
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: actions/checkout@v2 # v2.1.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: actions/setup-node@master # v1.2.3
      - run: |
          npm install
          npm build
      # ok: brave-third-party-action-not-pinned-to-commit-sha
      - uses: ./.github/actions/do-a-local-action
        with:
          arg1: ${{ secrets.supersecret1 }}
      # ok: brave-third-party-action-not-pinned-to-commit-sha
      - uses: completely/fakeaction@5fd3084fc36e372ff1fff382a39b10d03659f355 # v1.2.3
        with:
          arg2: ${{ secrets.supersecret2 }}
      # ok: brave-third-party-action-not-pinned-to-commit-sha
      - uses: docker://alpine@sha256:402d21757a03a114d273bbe372fa4b9eca567e8b6c332fa7ebf982b902207242 # v1.2.3
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: completely/fakeaction@5fd3084 # v1.2.3
        with:
          arg2: ${{ secrets.supersecret2 }}
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: completely/fakeaction@5fd3084
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: fakerepo/comment-on-pr@v1
        with:
          message: |
            Thank you!
      # ok: brave-third-party-action-not-pinned-to-commit-sha
      - uses: brave-intl/test@v1
      # ok: brave-third-party-action-not-pinned-to-commit-sha
      - uses: brave/test@v1
      # ok: brave-third-party-action-not-pinned-to-commit-sha
      - uses: brave-experiments/test@v1
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: aws-actions/test@v1
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: github/test@v1
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: ruby/setup-ruby@v1
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: slackapi/slack-github-action@v1.24.0
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: fakerepo/comment-on-pr
        with:
          message: |
            Thank you!
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: docker://gcr.io/cloud-builders/gradle
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
      - uses: docker://alpine:3.8
      - name: Notify Slack of success
      # ruleid: brave-third-party-action-not-pinned-to-commit-sha
        uses: 8398a7/action-slack@28ba43ae48961b90635b50953d216767a6bea486

  build2:
    name: Build and test using a local workflow
    # ok: brave-third-party-action-not-pinned-to-commit-sha
    uses: ./.github/workflows/use_a_local_workflow.yml@master
    secrets: inherit
    with:
      examplearg: true
