# action that add runtime as a custom property
# to all repositories in this organization
name: add-runtime-custom-property
description: Add Runtime as Custom Property to Repositories
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  static_repositories:
    description: 'Repositories that will have a `static` runtime'
    required: true
  runtime_directory:
    description: 'Directory where runtime files are stored'
    required: true
  debug:
    description: 'Debug mode'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: '22.x'
    - id: npm
      run: cd ${{ github.action_path }}/../..; npm ci
      shell: bash
    - name: run
      id: run
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        DEBUG: ${{ (inputs.debug == 'true' || runner.debug) && 'true' || 'false'}}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const actionPath = '${{ github.action_path }}/../../'
          const inputs = ${{ toJson(inputs) }}

          const script = require('${{ github.action_path }}/action.cjs')
          await script({github, context, inputs, actionPath, core,
            debug: process.env.DEBUG === 'true'})
