# action that add runtime as a custom property
# to all repositories in this organization
name: add-runtime-custom-property
description: Add Runtime as Custom Property to Repositories
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  static_repositories:
    description: 'Repositories that will have a `static` runtime'
    required: true
  runtime_directory:
    description: 'Directory where runtime files are stored'
    required: true
  debug:
    description: 'Debug mode'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: '24.x'
    - id: npm
      run: cd ${{ github.action_path }}/../..; npm ci
      shell: bash
    - name: run
      id: run
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        DEBUG: ${{ (inputs.debug == 'true' || runner.debug) && 'true' || 'false'}}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const actionPath = '${{ github.action_path }}/../../'
          const inputs = ${{ toJson(inputs) }}

          const script = require('${{ github.action_path }}/action.cjs')
          await script({github, context, inputs, actionPath, core,
            debug: process.env.DEBUG === 'true'})
