# action that runs monthly and check if all repositories in the organization are following the renovate central configuration
# to all repositories in this organization
name: renovate-sanity-check
description: Renovate Sanity Check
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  slack_token:
    description: 'Slack token'
    required: true
  debug:
    description: 'Debug mode'
    default: "false"
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: '24.x'
    - id: npm
      run: cd ${{ github.action_path }}/../..; npm ci
      shell: bash
    - name: run
      id: run
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        DEBUG: ${{ (inputs.debug == 'true' || runner.debug) && 'true' || 'false'}}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const actionPath = '${{ github.action_path }}/../../'
          const inputs = ${{ toJson(inputs) }}

          const script = require('${{ github.action_path }}/action.cjs')
          await script({github, context, inputs, actionPath, core,
            debug: process.env.DEBUG === 'true'})
