name: 'Opengrep Compare'
description: 'Compare Opengrep findings between base branch and current branch, or scan external repository'
inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  base_ref:
    description: 'Base branch to compare against (defaults to PR base or main)'
    required: false
    default: 'main'
  target_repo:
    description: 'External repository to scan (e.g., brave/brave-core). If set, clones and scans this repo.'
    required: false
  target_path:
    description: 'Subdirectory within target_repo to scan (optional)'
    required: false
  local_target:
    description: 'Local directory to scan instead of cloning (skips clone, useful if target is already checked out)'
    required: false
  compare_rules:
    description: 'Compare base branch rules vs current branch rules (default: true)'
    required: false
    default: 'true'
  changed_rules_only:
    description: 'Only scan with modified/added rule files (default: true)'
    required: false
    default: 'true'
outputs:
  new_findings_count:
    description: 'Number of new Opengrep findings from rule changes'
    value: ${{ steps.script.outputs.new_findings_count }}
  has_new_findings:
    description: 'Whether there are new findings (true/false)'
    value: ${{ steps.script.outputs.has_new_findings }}
  percentage_increase:
    description: 'Percentage increase in findings compared to base branch'
    value: ${{ steps.script.outputs.percentage_increase }}
  base_findings:
    description: 'Number of findings in base branch'
    value: ${{ steps.script.outputs.base_findings }}
  total_findings:
    description: 'Total findings in current branch'
    value: ${{ steps.script.outputs.total_findings }}
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.13'

    - name: Cache opengrep
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.opengrep
        key: opengrep-v1.11.2-${{ runner.os }}

    - name: Install Opengrep
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |-
          const path = require('path')
          const installOpengrep = (await import(path.join('${{ github.action_path }}', '../../src/installOpengrep.js'))).default
          await installOpengrep()

    - name: Install Python dependencies
      shell: bash
      run: |
        python3 -m pip --disable-pip-version-check install -r ${{ github.action_path }}/../../requirements.txt

    - name: Run Opengrep Comparison
      id: script
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        github-token: ${{ inputs.github_token }}
        script: |-
          const actionPath = '${{ github.action_path }}/../../'
          const inputs = ${{ toJson(inputs) }}

          const script = require('${{ github.action_path }}/action.cjs')
          await script({github, context, inputs, actionPath, core})
